export default [
    {
        pagePath:"/pages/index/index",
        text:"推荐",
        iconPath:"https://ak48.qizue.com/assets/emotions/icons/tabbar/fire.svg",
        selectedIconPath:"https://ak48.qizue.com/assets/emotions/icons/tabbar/fire-active.svg"
    },
    {
        pagePath:"/pages/category/index",
        text:"分类",
        iconPath:"https://ak48.qizue.com/assets/emotions/icons/tabbar/category-management.svg",
        selectedIconPath:"https://ak48.qizue.com/assets/emotions/icons/tabbar/category-management-active.svg"
    },
    {
        pagePath:"/pages/diy/index",
        text:"DIY表情包",
        iconPath:"https://ak48.qizue.com/assets/emotions/icons/tabbar/kitchen-knife.png",
        selectedIconPath:"https://ak48.qizue.com/assets/emotions/icons/tabbar/kitchen-knife-active.png"
    }
]
